/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.AlumnoData;
import Entidades.Alumno;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matiSqui
 */
public class InternalAlumnadoH extends javax.swing.JInternalFrame {

          private DefaultTableModel modelo = new DefaultTableModel();
          private AlumnoData aluData = new AlumnoData();
          private Alumno alumnoActual = null;
          
   
    /**
     * Creates new form InterAlumnadoH
     */
    public InternalAlumnadoH() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btAlumnadoTrue = new javax.swing.JButton();
        btAlumnadoFalse = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAlumnado = new javax.swing.JTable();
        btSalir = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Alumnado Historico");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Buscar segun su estado");

        btAlumnadoTrue.setText("Alumnado Activo");
        btAlumnadoTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlumnadoTrueActionPerformed(evt);
            }
        });

        btAlumnadoFalse.setText("Alumnado Inactivo");
        btAlumnadoFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlumnadoFalseActionPerformed(evt);
            }
        });

        jTableAlumnado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableAlumnado);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        labelMensaje.setText("\"   \"");
        labelMensaje.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAlumnadoTrue)
                            .addComponent(jLabel2))
                        .addGap(88, 88, 88)
                        .addComponent(btAlumnadoFalse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelMensaje)))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalir)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btSalir))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlumnadoTrue)
                    .addComponent(btAlumnadoFalse))
                .addGap(64, 64, 64)
                .addComponent(labelMensaje)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlumnadoFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlumnadoFalseActionPerformed
 
        labelMensaje.setText("Resultado de la busqueda de alumnado: [Inactivo]");
        
        modelo.setRowCount(0);
        mostrarDatosFalse();
     
    }//GEN-LAST:event_btAlumnadoFalseActionPerformed

    private void btAlumnadoTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlumnadoTrueActionPerformed
    
        labelMensaje.setText("Resultado de la busqueda de alumnado: [Activo]");

    modelo.setRowCount(0);
    mostrarDatosTrue();        
           
    }//GEN-LAST:event_btAlumnadoTrueActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        
        dispose();

    }//GEN-LAST:event_btSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlumnadoFalse;
    private javax.swing.JButton btAlumnadoTrue;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableAlumnado;
    private javax.swing.JLabel labelMensaje;
    // End of variables declaration//GEN-END:variables

    public void armarCabecera(){
        
        modelo.addColumn("idAlumno");
        modelo.addColumn("DNI");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        modelo.addColumn("Estado");
        
        jTableAlumnado.setModel(modelo);
        
    }


  public void mostrarDatosTrue() {
   
    modelo.setRowCount(0);

   
    for (Alumno alumno : aluData.listarAlumnos()) {
        
        Object[] fila = new Object[5];
        fila[0] = alumno.getIdAlumno();
        fila[1] = alumno.getDni();
        fila[2] = alumno.getApellido();
        fila[3] = alumno.getNombre();
        fila[4] = alumno.isActivo() ? "Activo" : "Inactivo";  

    
        modelo.addRow(fila);
    }

    
    
}
    public void mostrarDatosFalse() {
 
    modelo.setRowCount(0);

   
    for (Alumno alumno : aluData.listarAlumnosIn()) {
        
        Object[] fila = new Object[5];
        fila[0] = alumno.getIdAlumno();
        fila[1] = alumno.getDni();
        fila[2] = alumno.getApellido();
        fila[3] = alumno.getNombre();
        fila[4] = alumno.isActivo() ? "Activo" : "Inactivo";  

        
        modelo.addRow(fila);
    }

    
    
}
  
  
  
}