/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author matiSqui
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAlumnado = new javax.swing.JMenu();
        MenuAlumnos = new javax.swing.JMenuItem();
        MenuMaterias = new javax.swing.JMenuItem();
        MenuAlumnadoH = new javax.swing.JMenuItem();
        MenuListaMate = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        MenuAlumnado.setText("Administracion");

        MenuAlumnos.setText("Alumnos");
        MenuAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlumnosActionPerformed(evt);
            }
        });
        MenuAlumnado.add(MenuAlumnos);

        MenuMaterias.setText("Materias");
        MenuMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMateriasActionPerformed(evt);
            }
        });
        MenuAlumnado.add(MenuMaterias);

        MenuAlumnadoH.setText("Alumnado Historico");
        MenuAlumnadoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlumnadoHActionPerformed(evt);
            }
        });
        MenuAlumnado.add(MenuAlumnadoH);

        MenuListaMate.setText("Listado Materias");
        MenuListaMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListaMateActionPerformed(evt);
            }
        });
        MenuAlumnado.add(MenuListaMate);

        jMenuBar1.add(MenuAlumnado);

        jMenu2.setText("Inscripciones");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlumnosActionPerformed

        InternalAlumno internalAlumno = new InternalAlumno();
        escritorio.add(internalAlumno);
        internalAlumno.setVisible(true);
        

    }//GEN-LAST:event_MenuAlumnosActionPerformed

    private void MenuAlumnadoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlumnadoHActionPerformed

        InternalAlumnadoH internalAlumnado = new InternalAlumnadoH();
        escritorio.add(internalAlumnado);
        internalAlumnado.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAlumnadoHActionPerformed

    private void MenuMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMateriasActionPerformed
        
        InternalMaterias internalMaterias = new InternalMaterias();
        escritorio.add(internalMaterias);
        internalMaterias.setVisible(true);

        
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuMateriasActionPerformed

    private void MenuListaMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListaMateActionPerformed

        InternalListaMaterias internalListaMate = new InternalListaMaterias();
        escritorio.add(internalListaMate);
        internalListaMate.setVisible(true);
               
    }//GEN-LAST:event_MenuListaMateActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAlumnado;
    private javax.swing.JMenuItem MenuAlumnadoH;
    private javax.swing.JMenuItem MenuAlumnos;
    private javax.swing.JMenuItem MenuListaMate;
    private javax.swing.JMenuItem MenuMaterias;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
